name: Build & Deploy Server Admin

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/server/admin/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Deploy
        run: echo "Deployed"